Repository COSMIC-SANTA/backend, pull requests merged in 2025-07, with the labels that each got.

#6 feat/5 : 생성, 수정 시간 저장에 필요한 클래스 구현
  backend/src/main/java/SANTA/backend/global/common/BaseEntity.java
Labels: 💻 기능

#10 Feat/9: 회원 메달/ 그룹을 구현합니다.
  backend/src/main/java/SANTA/backend/core/auth/service/CustomOauth2UserService.java
  backend/src/main/java/SANTA/backend/core/auth/service/CustomUserDetailsService.java
  backend/src/main/java/SANTA/backend/core/auth/service/JoinService.java
  backend/src/main/java/SANTA/backend/core/group/application/GroupService.java
  backend/src/main/java/SANTA/backend/core/group/domain/Group.java
  backend/src/main/java/SANTA/backend/core/group/domain/GroupRepository.java
  backend/src/main/java/SANTA/backend/core/group/domain/Interest.java
  backend/src/main/java/SANTA/backend/core/group/domain/Level.java
  backend/src/main/java/SANTA/backend/core/group/entity/GroupEntity.java
  backend/src/main/java/SANTA/backend/core/group/entity/UserGroupEntity.java
  backend/src/main/java/SANTA/backend/core/group/infra/GroupJpaRepository.java
  backend/src/main/java/SANTA/backend/core/user/application/UserService.java
  backend/src/main/java/SANTA/backend/core/user/application/UserServiceImpl.java
  backend/src/main/java/SANTA/backend/core/user/domain/Medal.java
  backend/src/main/java/SANTA/backend/core/user/domain/UserRepository.java
  backend/src/main/java/SANTA/backend/core/user/entity/UserEntity.java
  backend/src/main/java/SANTA/backend/core/user/infra/UserJpaRepository.java
  backend/src/main/java/SANTA/backend/global/jwt/JWTFilter.java
  backend/src/main/java/SANTA/backend/global/package-info.java
Labels: 💻 기능, 💡 제안

#28 Refactor/24: Course 없이도 Place 객체 생성 가능하도록 리팩토링
  backend/src/main/java/SANTA/backend/core/basePlace/entity/BasePlaceEntity.java
  backend/src/main/java/SANTA/backend/core/cafe/entity/CafeEntity.java
  backend/src/main/java/SANTA/backend/core/restaurant/entity/RestaurantEntity.java
  backend/src/main/java/SANTA/backend/core/spot/entity/SpotEntity.java
  backend/src/main/java/SANTA/backend/core/stay/entity/StayEntity.java
Labels: 🔧 리팩터링
